# Generated by Django 6.1.1 on 2026-09-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_savedjob'),
        ('candidates', '0002_candidate_user'),
        ('jobs', '0003_job_education_job_key_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('candidate', 'application_number'), name='unique_candidate_application_number'),
        ),
    ]
