# Generated by Django 6.1.1 on 2026-09-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cab_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='shift',
            field=models.CharField(choices=[('Day Shift', 'Day Shift'), ('Night Shift', 'Night Shift'), ('Rotational Shift', 'Rotational Shift'), ('Flexible Shift', 'Flexible Shift')], default='Day Shift', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='shift_timing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('Work From Office', 'Work From Office'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='Work From Office', max_length=30),
        ),
    ]
