# Generated by Django 6.1.1 on 2026-09-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_cab_available_job_shift_job_shift_timing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='key_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='what_were_looking_for',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='what_youll_be_doing',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
    ]
